import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Auto-generate sidebar from the docs folder structure
const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // Generate from root of docs folder
    },
  ],
};

export default sidebars;
