import type { SidebarsConfig, PropSidebarItem } from '@docusaurus/plugin-content-docs';

// Auto-generate sidebar from the docs folder structure
const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // Generate from root of docs folder
      // Hide archive folder from sidebar
      filterItems: (items: PropSidebarItem[]) => {
        return items.filter((item) => {
          if (item.type === 'category') {
            return item.label.toLowerCase() !== 'archive';
          }
          return true;
        });
      },
    } as any,
  ],
};

export default sidebars;
